name: Terraform

on:
  #push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        - uses: actions/checkout@v2
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get -y install wget unzip
          wget https://releases.hashicorp.com/terraform/latest/terraform_latest_linux_amd64.zip
          unzip terraform_latest_linux_amd64.zip
          mv terraform /usr/local/bin/
          rm terraform_latest_linux_amd64.zip
      - name: Run Terraform
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
